### ISSUE TITLE
mimetype -M returns "video/mp4" for an .m4a audio file if it has embedded cover art

### ISSUE THREAD

**Issue by bp0** [mbeijen/File-MimeInfo#10]
An m4a file with a jpeg image embedded in the covr tag causes mimetype -M to return video/mp4 when mimetype without -M returns audio/m4a. This removes the usefulness of using mimetype to verify that some m4a is actually what it claims to be, an mp4 with only audio.

**Comment by mbeijen** [comment]
The magic data comes from https://gitlab.freedesktop.org/xdg/shared-mime-info/ -- any problems with mimetype not recognizing files should be fixed in the shared-mime-info data.
