### ISSUE TITLE
Not identifying file of the type text/html if file does not contain the "<html>" tag.

### ISSUE THREAD

**Issue by jg0000** [mbeijen/File-MimeInfo#19]
> lsb_release -a
> LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
> Distributor ID: Ubuntu
> Description:    Ubuntu 14.04.3 LTS
> Release:    14.04
> Codename:   trusty
> 
> aptitude show libfile-mimeinfo-perl
> Package: libfile-mimeinfo-perl  
> State: installed
> Automatically installed: no
> Version: 0.22-1
> Priority: optional
> Section: perl
> Maintainer: Ubuntu Developers ubuntu-devel-discuss@lists.ubuntu.com
> Architecture: all
> Uncompressed Size: 142 k
> Depends: perl, libfile-basedir-perl, libfile-desktopentry-perl, shared-mime-info
> Description: Perl module to determine file types
>  File::MimeInfo can be used to determine the mime type of a file. It tries to implement the freedesktop specification for
>  a shared MIME database. 

 This package also contains two related utilities: 
- mimetype: determine a file's mimetype 
- mimeopen: open files according to their mimetype
  Homepage: https://metacpan.org/release/File-MimeInfo

If a file does not contain the `<html>` tag, /usr/bin/mimetype identifies the file as text/plain. /usr/bin/file seems to be more intelligent, or more tolerant, in this regard.

**Comment by mbeijen** [comment]
Can you please provide an example of a case that `mimetype` does NOT handle, but `/usr/bin/file` does handle correctly?

**Comment by jg0000** [comment]
Hi Michiel

Please see attached test file.

My tests:

# /usr/bin/mimetype /tmp/mimetestfile 
/tmp/mimetestfile: text/plain

# file /tmp/mimetestfile
/tmp/mimetestfile: HTML document, ISO-8859 text, with very long lines


Regards,

Jie 

* Michiel Beijen <notifications@github.com> wrote:

> Date: Thu, 31 Dec 2015 02:07:00 -0800
> From: Michiel Beijen <notifications@github.com>
> To: mbeijen/File-MimeInfo <File-MimeInfo@noreply.github.com>
> CC: jg0000 <j.gao@sydney.edu.au>
> Subject: Re: [File-MimeInfo] Not identifying file of the type text/html if
>  file does not contain the "<html>" tag. (#19)
> 
> Can you please provide an example of a case that `mimetype` does NOT handle, but `/usr/bin/file` does handle correctly?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mbeijen/File-MimeInfo/issues/19#issuecomment-168161023

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><style type="text/CSS">
body {
	FONT-FAMILY : Verdana, Arial, Helvetica, sans-serif;
	FONT-WEIGHT: none;
	TEXT-DECORATION: none;
	FONT-SIZE: 11px;
}
</style><body bgcolor="#FFFFFF" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td><table width="750" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td><table width="750" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><a href="http://www.cablechick.com.au/?ref=1044&amp;tc=201512-xmas15-04"><img src="https://www.cablechick.com.au/newsletters/xmas15/xmas15-ny-logo.jpg" alt="&#55357;&#56986; FREE SHIPPING - TODAY ONLY" width="574" height="94" border="0" style="display: block;"></a></td>
        <td width="176" height="94" align="center" valign="top" background="https://www.cablechick.com.au/newsletters/xmas15/xmas15-ny-social.jpg"><a href="http://www.facebook.com/TheCableChick"><img width="18" height="21" border="0" src="https://www.cablechick.com.au/newsletters/tiny-facebook.gif" alt=" "></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://twitter.com/cable_chick"><img width="18" height="21" border="0" src="https://www.cablechick.com.au/newsletters/tiny-twitter.gif" alt=" "></a></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td align="center"><a href="http://www.cablechick.com.au/?ref=1044&amp;tc=201512-xmas15-04"><img src="https://www.cablechick.com.au/newsletters/xmas15/xmas15-ny-promo1.jpg" alt="Hurry! Offer ends tonight!" width="750" height="215" border="0" style="display: block;"></a><a href="http://www.cablechick.com.au/?ref=1044&amp;tc=201512-xmas15-04"><img src="https://www.cablechick.com.au/newsletters/xmas15/xmas15-ny-promo2.jpg" alt="Free Regular Shipping or $5.95 Express - TODAY ONLY" width="750" height="215" border="0" style="display: block;"></a></td>
  </tr>
  <tr>
    <td align="center"><img src="https://www.cablechick.com.au/newsletters/hrule.gif" width="708" height="12" border="0"></td>
  </tr>
  <tr>
    <td><span style="font-family: Verdana,Arial,Helvetica,sans-serif; color: rgb(102, 102, 102); font-size: 11px;">Thanks for reading!<br>
        <img src="https://cablechick.com.au/img/cable-chick-signature-small.gif" alt="Cable Chick Signature" vspace="4" border="0"><br>
        <strong>Cable Chick and the Team</strong></span></td>
  </tr>
  <tr>
    <td>
<div align="center">
    <div style="width:600px; font-size:14px; font-family: 'Lucida Sans', 'Verdana', 'Helvetica', 'sans-serif';" align="left">
        <h1><a href="https://www.cablechick.com.au/blog/" style="font-family: 'Open Sans Condensed', 'Verdana', 'Helvetica', 'sans-serif'; text-decoration:none; color:#000;">Cable Chick's Latest Blogs</a></h1>
        <div style="margin:5px; padding:10px; width:600px; border-top:1px solid #ddd;" align="left">
            <div style="float:left; width:150px; margin-top:6px; -moz-border-radius: 10px; -webkit-border-radius: 10px; -khtml-border-radius: 10px; border-radius: 10px; width:150; height:75; overflow:hidden;">
                <a href="https://www.cablechick.com.au/blog/what-is-usb-otg/"><img src="https://www.cablechick.com.au/resources/what-is-usb-otg-and-what-can.jpg" border="0" width="150" height="75" alt="What is USB OTG and What Can It Do?"></a>
            </div>
            <div style="float:left; margin:0px 0px 0px 20px; width:430px;">
                <h3><a href="https://www.cablechick.com.au/blog/what-is-usb-otg/" style="line-height:15px; font-family: 'Open Sans Condensed', 'Verdana', 'Helvetica', 'sans-serif'; text-decoration:none; color:#000;">What is USB OTG and What Can It Do?</a></h3>
                <div style="padding:0px 0px 12px 0px;">
                    USB OTG (On-the-Go) is a powerful feature of many Android smartphones and tablets. Learn how to take advantage of it today! &nbsp; <a href="https://www.cablechick.com.au/blog/what-is-usb-otg/">Read More</a>
                </div>
            </div>
            <div style="clear:both;"></div>
        </div>
        <div style="margin:5px; padding:10px; width:600px; border-top:1px solid #ddd;" align="left">
            <div style="float:left; width:150px; margin-top:6px; -moz-border-radius: 10px; -webkit-border-radius: 10px; -khtml-border-radius: 10px; border-radius: 10px; width:150; height:75; overflow:hidden;">
                <a href="https://www.cablechick.com.au/blog/multi-coloured-cat6-cat6a-500mhz-cables/"><img src="https://www.cablechick.com.au/resources/product-launch-cat6-colour.jpg" border="0" width="150" height="75" alt="Product Launch - Cat6 Colour Range &amp; New Cat6A 500Mhz cables"></a>
            </div>
            <div style="float:left; margin:0px 0px 0px 20px; width:430px;">
                <h3><a href="https://www.cablechick.com.au/blog/multi-coloured-cat6-cat6a-500mhz-cables/" style="line-height:15px; font-family: 'Open Sans Condensed', 'Verdana', 'Helvetica', 'sans-serif'; text-decoration:none; color:#000;">Product Launch - Cat6 Colour Range &amp; New Cat6A 500Mhz cables</a></h3>
                <div style="padding:0px 0px 12px 0px;">
                    Colour code your home and office networks with our new rainbow range of Category 6 cables and travel to the future with CAT6A! &nbsp; <a href="https://www.cablechick.com.au/blog/multi-coloured-cat6-cat6a-500mhz-cables/">Read More</a>
                </div>
            </div>
            <div style="clear:both;"></div>
        </div>
        <div style="margin:5px; padding:10px; width:600px; border-top:1px solid #ddd;" align="left">
            <div style="float:left; width:150px; margin-top:6px; -moz-border-radius: 10px; -webkit-border-radius: 10px; -khtml-border-radius: 10px; border-radius: 10px; width:150; height:75; overflow:hidden;">
                <a href="https://www.cablechick.com.au/blog/why-does-my-amplifier-use-negative-db-for-volume/"><img src="https://www.cablechick.com.au/resources/why-does-my-amplifier-use.jpg" border="0" width="150" height="75" alt="Why does my Amplifier use Negative dB for Volume?"></a>
            </div>
            <div style="float:left; margin:0px 0px 0px 20px; width:430px;">
                <h3><a href="https://www.cablechick.com.au/blog/why-does-my-amplifier-use-negative-db-for-volume/" style="line-height:15px; font-family: 'Open Sans Condensed', 'Verdana', 'Helvetica', 'sans-serif'; text-decoration:none; color:#000;">Why does my Amplifier use Negative dB for Volume?</a></h3>
                <div style="padding:0px 0px 12px 0px;">
                    Have you ever wondered why your home theatre receiver shows volume as a negative number? Wonder no more! &nbsp; <a href="https://www.cablechick.com.au/blog/why-does-my-amplifier-use-negative-db-for-volume/">Read More</a>
                </div>
            </div>
            <div style="clear:both;"></div>
        </div>
        <div style="border-top:1px solid #ddd; width:600px;"></div>
		<div align="right">
    		<a href="https://www.cablechick.com.au/blog/" style="text-decoration:none;">See more articles &amp; blogs...</a>
        </div>
    </div>
</div></td>
  </tr>
  <tr>
    <td align="center"><p><a href="http://www.cablechick.com.au/shipping/?ref=1044&amp;tc=201512-xmas15-04"><img src="https://www.cablechick.com.au/newsletters/shipping-bar.jpg" alt="Flat Rate Shipping on Regular and Express Services" width="580" height="80" border="0"></a><br>
                                        <br>
                                      <img src="https://www.cablechick.com.au/newsletters/hrule.gif" width="708" height="12" border="0"></p>
                 <p><span style="font-family: Verdana,Arial,Helvetica,sans-serif; color:#666; font-size: 11px;">Please read the full <span style="color:#666"><a href="http://www.cablechick.com.au/terms/?ref=1044&amp;tc=termslink" style="color:#666">terms and conditions</a></span> available on our website.<br>
Savings based on RRP. Prices and Specifications subject to change without notice.<br>
Promotion valid until 11:59pm AEST Friday January 1st 2016 
                   or until sold out. Sorry, no rainchecks. </span></p>
                                      <table width="350" cellspacing="0" cellpadding="0" border="0" align="center">
                                        <tbody>
                                          <tr>
                                            <td valign="middle" height="65" align="center"><a href="http://www.cablechick.com.au/?ref=1044&amp;tc=201512-xmas15-04"><img width="182" height="65" border="0" alt="Cable Chick Website" src="https://www.cablechick.com.au/cable-chick-logo-sml.gif"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.facebook.com/TheCableChick"><img width="51" height="51" border="0" style="margin-bottom: 8px;" alt="Facebook" src="https://www.cablechick.com.au/newsletters/facebook.gif"></a> &nbsp;&nbsp;&nbsp;&nbsp; <a href="http://twitter.com/Cable_Chick"><img width="51" height="51" border="0" style="margin-bottom: 8px;" alt="Twitter" src="https://www.cablechick.com.au/newsletters/twitter.gif"></a></td>
                                          </tr>
                                        </tbody>
                                      </table><img width="595" height="52" alt="Cable Chick Accepts: American Express, Visa, Mastercard, Paypal and more" src="https://www.cablechick.com.au/newsletters/paymentoptions.gif">
                                      <p><img src="https://www.cablechick.com.au/newsletters/xmas-2011/hrule.gif" width="708" height="12"></p>
                                      <p style="font-size: 10px; color:#666; font-family: Verdana,Arial,Helvetica,sans-serif;">Product and Gift stock is limited and may sell out at any time. Prices and Prizes are subject to change.<br>
                                      � 2006-2016 <a href="http://www.cablechick.com.au?ref=1044&amp;tc=201512-xmas15-04">www.CableChick.com.au</a>. All rights reserved.</p>
                                    <p style="font-size: 10px; color:#666; font-family: Verdana,Arial,Helvetica,sans-serif;">This message was sent to the following email address: <a href="mailto:j.gao@sydney.edu.au">j.gao@sydney.edu.au</a> <br>
                                    We hope you find this message useful, however if you would rather not receive any more<br>
                                    Cable Chick Newsletters, please <a href="http://www.cablechick.com.au/subscriptions.php?sub_email=j.gao@sydney.edu.au&amp;eid=34251">click here to unsubscribe</a>. Or <a href="http://www.cablechick.com.au/login/?ref=1044&amp;tc=loginlink">Log in</a> to manage your Subscriptions.</p></td>
  </tr>
  </table>
</td>
  </tr>
</table>

</body>

**Comment by mbeijen** [comment]
Determining that a file is an HTML file when it is called `something` and not `something.html` and it merely contains some tags that look like HTML but not the required `<html>` - I'm not sure if I'd find it correct, it might lead to other sorts of problems. `File::MimeInfo` does not need to be bug-compatible with `/usr/bin/file`. Closing.
