### ISSUE TITLE
Global default applications are ignored by mimeopen

### ISSUE THREAD

**Issue by marmarek** [mbeijen/File-MimeInfo#20]
Standard http://standards.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.html defines that default application associations should be first searched in $XDG_CONFIG_HOME, then $XDG_DATA_HOME (among other directories). This makes it possible to ship some distribution-wide defaults, while allowing user to choose some personal preferences.
Currently `mimeopen` ignores the later files - when no personal preferences are set, it basically choose "random" application (first on the list) as default (when `-n` is used). Even if some system-wide default is set.

**Comment by mbeijen** [comment]
Fixed by Celti!
