### ISSUE TITLE
need pod clarification

### ISSUE THREAD

**Issue by martinthurn-LFT** [mbeijen/File-MimeInfo#22]
The documentation says (many times) "mimetype($file)".  What EXACTLY is $file???  The name of a file?  A FileHandle or IO::File object?  A scalar holding the contents of a file?  Please clarify!

**Comment by mbeijen** [comment]
More POD explanation was added in https://github.com/mbeijen/File-MimeInfo/commit/9abf71e90f378c37142109adad6a3425f9d404cf
