### ISSUE TITLE
[PATCH] spelling fix

### ISSUE THREAD

**Issue by gregoa** [mbeijen/File-MimeInfo#25]
In Debian we are currently applying the following patch to
File-MimeInfo.
We thought you might be interested in it too.

    Description: spelling fix
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-11-28
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libfile-mimeinfo-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by mbeijen** [comment]
Thanks, applied in https://github.com/mbeijen/File-MimeInfo/commit/4bed25732bfb4d15fa09b877f39505f686d0d1f8
