### ISSUE TITLE
bash code is detected as audio/x-mod

### ISSUE THREAD

**Issue by HybridDog** [mbeijen/File-MimeInfo#39]
I noticed that today my .bash_history file is shown as an Amiga-SoundTracker-Audio file in pcmanfm. These first three lines make mimetype -M detect it as audio/x-mod:
```
if [[ "hallo" =~ "hallo" ]] ; then echo test; fi
if [[ "hello" =~ "hallo" ]] ; then echo test; fi
if [[ "hello" =~ "h.llo" ]] ; then echo test; fi
```
I hope this is the right place to put this issue.

**Comment by mbeijen** [comment]
The magic data comes from https://gitlab.freedesktop.org/xdg/shared-mime-info/ -- any problems with mimetype not recognizing files should be fixed in the shared-mime-info data.

**Comment by HybridDog** [comment]
https://gitlab.freedesktop.org/xdg/shared-mime-info/-/issues/144
