### ISSUE TITLE
`mimeopen` uses wrong exit code even if execution went correctly

### ISSUE THREAD

**Issue by purplebar0** [mbeijen/File-MimeInfo#54]
For some reason, this `exit 7` is executed even if execution went correctly:

https://github.com/mbeijen/File-MimeInfo/blob/cd55818f754a74e921db2e37b951b59b4916b408/mimeopen#L185

Removing the offending line results in correct execution and the correct error code (0).

This is a problem since `xdg-open`, if it doesn't detect a known desktop environment, uses `mimeopen` if it's available, and checks its exit code. If it's nonzero, execution continues as if `mimeopen` failed, resulting in `xdg-open` opening the file multiple times.

This is described in more detail on [Gentoo Forums](https://forums.gentoo.org/viewtopic-p-8792910.html?sid=782b75ad0f840a9bd225f32261a55880), albeit nobody pointed out it was an issue with `mimeopen`.

**Comment by slatian** [comment]
I can confirm that this causes a problem with xdg-open.
