### ISSUE TITLE
mimeapps.list Standard

### ISSUE THREAD

**Issue by Smylers** [mbeijen/File-MimeInfo#8]
Hi there. Thanks for `mimeopen` and associated modules.

From the docs for `File::MimeInfo::Applications`:

> At present the file with defaults is _$XDG_DATA_HOME/applications/defaults.list_. This file is not specified in any freedesktop spec and if it gets standardized it should probably be located in `$XDG_CONFIG_HOME`.

There now [seems to be a standard](http://standards.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.html), and the chosen filename is _mimeapps.list_.

As expected, symlinking _defaults.list_ to _mimeapps.list_ makes `mimeopen` use the preferences I've expressed with various graphical file managers.

Well done also for anticipating the directory move.

**Comment by silverhammermba** [comment]
An update to this issue, the standard location is `$XDG_CONFIG_HOME/mimeapps.list` i.e. `~/.config/mimeapps.list`.

A nice non-breaking way to implement this would be to read both locations and have the non-deprecated location take precedence.

**Comment by oldgaro** [comment]
Thanks!
